sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: pip install -e .[test]
script: python setup.py test
after_success:
- coverage xml
- coveralls
- python-codacy-coverage -r coverage.xml
